### to use install this vs code extension
### REST Client

### get all users
GET http://localhost:5011/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzA1MzM4ODgyLCJleHAiOjE3MDU0MjUyODJ9.I1Jo9VCRmU-s6jaHJxNrZTUpCYMyM9irIQY-Ly2Y5vE




### Login
POST http://localhost:5011/user/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "jD7R)$)$?Q,bQ8g"
}


### get all products

GET http://localhost:5011/products/

### search for products

GET http://localhost:5011/products/search/sm

